services:
  # 1. O Banco de Dados (PostgreSQL)
  db:
    image: postgres:14.22
    container_name: economize_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: economize_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Interface Visual para o Banco (Opcional, mas muito útil)
  pgadmin:
    image: dpage/pgadmin4
    container_name: economize_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. O Microsserviço de IA (Python FastAPI)
  # ai-service:
  #   build:
  #     context: ./ai-service
  #     dockerfile: Dockerfile.dev
  #   container_name: economize_ia
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     # Espelha a pasta local para dentro do container (garante o hot-reload)
  #     - ./ai-service:/app
  #   environment:
  #     # Não passamos o banco aqui, porque quem fala com o banco é o Next.js
  #     - OPENAI_API_KEY=sua_chave_futura_aqui

volumes:
  pgdata: # Garante que seus dados não sumam se você desligar o container
