CREATE TABLE TB001_USUARIO (
    ID_REGISTRO UUID NOT NULL,
    STR_NOME VARCHAR(120) NOT NULL,
    STR_EMAIL VARCHAR(320) NOT NULL,
    STR_SENHA_HASH VARCHAR(255) NOT NULL,
    STR_TIMEZONE VARCHAR(80) NOT NULL,
    STR_STATUS VARCHAR(20) NOT NULL,
    DHR_EXCLUSAO TIMESTAMPTZ,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK001_USUARIO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK001_01_EMAIL UNIQUE (STR_EMAIL),
    CONSTRAINT CK001_01_STATUS CHECK (STR_STATUS IN ('ATIVO', 'BLOQUEADO')),
    CONSTRAINT CK001_02_NOME CHECK (BTRIM(STR_NOME) <> ''),
    CONSTRAINT CK001_03_EMAIL_NORMALIZADO CHECK (STR_EMAIL = LOWER(BTRIM(STR_EMAIL)))
);

CREATE TABLE TB002_CONTA_FINANCEIRA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    STR_NOME VARCHAR(120) NOT NULL,
    STR_MOEDA VARCHAR(3) NOT NULL,
    DEC_SALDO_INICIAL NUMERIC(19,4) NOT NULL,
    DAT_SALDO_INICIAL DATE NOT NULL,
    BOL_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK002_CONTA_FINANCEIRA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK002_01_ID_USUARIO UNIQUE (ID_REGISTRO, ID_USUARIO),
    CONSTRAINT FK002_01_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB001_USUARIO (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT CK002_01_NOME CHECK (BTRIM(STR_NOME) <> ''),
    CONSTRAINT CK002_02_MOEDA CHECK (STR_MOEDA ~ '^[A-Z]{3}$')
);

CREATE TABLE TB003_CATEGORIA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    ID_CATEGORIA_PAI UUID,
    STR_NOME VARCHAR(80) NOT NULL,
    STR_COR VARCHAR(20),
    BOL_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK003_CATEGORIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK003_03_ID_USUARIO UNIQUE (ID_REGISTRO, ID_USUARIO),
    CONSTRAINT FK003_01_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB001_USUARIO (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT FK003_02_CATEGORIA_PAI FOREIGN KEY (ID_CATEGORIA_PAI, ID_USUARIO) REFERENCES TB003_CATEGORIA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT CK003_01_NOME CHECK (BTRIM(STR_NOME) <> ''),
    CONSTRAINT CK003_02_AUTO_REFERENCIA CHECK (ID_CATEGORIA_PAI IS NULL OR ID_CATEGORIA_PAI <> ID_REGISTRO)
);

CREATE UNIQUE INDEX UK003_01_NOME_RAIZ ON TB003_CATEGORIA (ID_USUARIO, LOWER(STR_NOME)) WHERE ID_CATEGORIA_PAI IS NULL;
CREATE UNIQUE INDEX UK003_02_NOME_IRMA ON TB003_CATEGORIA (ID_USUARIO, ID_CATEGORIA_PAI, LOWER(STR_NOME)) WHERE ID_CATEGORIA_PAI IS NOT NULL;

CREATE TABLE TB004_GRUPO_RECORRENCIA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    STR_DESCRICAO VARCHAR(255) NOT NULL,
    STR_STATUS VARCHAR(20) NOT NULL,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK004_GRUPO_RECORRENCIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK004_01_ID_USUARIO UNIQUE (ID_REGISTRO, ID_USUARIO),
    CONSTRAINT FK004_01_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB001_USUARIO (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT CK004_01_STATUS CHECK (STR_STATUS IN ('ATIVO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT CK004_02_DESCRICAO CHECK (BTRIM(STR_DESCRICAO) <> '')
);

CREATE TABLE TB005_SEGMENTO_RECORRENCIA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    ID_GRUPO_RECORRENCIA UUID NOT NULL,
    ID_CONTA_FINANCEIRA UUID NOT NULL,
    ID_CATEGORIA UUID,
    STR_TIPO_TRANSACAO VARCHAR(20) NOT NULL,
    STR_DESCRICAO VARCHAR(255) NOT NULL,
    STR_OBSERVACOES VARCHAR(2000),
    DEC_VALOR NUMERIC(19,4) NOT NULL,
    DAT_DTSTART DATE NOT NULL,
    STR_RRULE VARCHAR(500) NOT NULL,
    INT_TOTAL_OCORRENCIAS INTEGER,
    STR_STATUS VARCHAR(20) NOT NULL,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK005_SEGMENTO_RECORRENCIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK005_01_ID_GRUPO_USUARIO UNIQUE (ID_REGISTRO, ID_GRUPO_RECORRENCIA, ID_USUARIO),
    CONSTRAINT FK005_01_GRUPO FOREIGN KEY (ID_GRUPO_RECORRENCIA, ID_USUARIO) REFERENCES TB004_GRUPO_RECORRENCIA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK005_02_CONTA FOREIGN KEY (ID_CONTA_FINANCEIRA, ID_USUARIO) REFERENCES TB002_CONTA_FINANCEIRA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK005_03_CATEGORIA FOREIGN KEY (ID_CATEGORIA, ID_USUARIO) REFERENCES TB003_CATEGORIA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT CK005_01_TIPO CHECK (STR_TIPO_TRANSACAO IN ('RECEITA', 'DESPESA')),
    CONSTRAINT CK005_02_STATUS CHECK (STR_STATUS IN ('ATIVO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT CK005_03_VALOR CHECK (DEC_VALOR > 0),
    CONSTRAINT CK005_04_RRULE CHECK (BTRIM(STR_RRULE) <> '' AND STR_RRULE NOT LIKE 'RRULE:%'),
    CONSTRAINT CK005_05_TOTAL CHECK (INT_TOTAL_OCORRENCIAS IS NULL OR INT_TOTAL_OCORRENCIAS > 0)
);

CREATE TABLE TB006_TRANSACAO (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    ID_CONTA_FINANCEIRA UUID NOT NULL,
    ID_CATEGORIA UUID,
    ID_GRUPO_RECORRENCIA UUID,
    ID_SEGMENTO_RECORRENCIA UUID,
    STR_TIPO VARCHAR(20) NOT NULL,
    STR_STATUS VARCHAR(20) NOT NULL,
    STR_DESCRICAO VARCHAR(255) NOT NULL,
    STR_OBSERVACOES VARCHAR(2000),
    DEC_VALOR NUMERIC(19,4) NOT NULL,
    DAT_VENCIMENTO DATE NOT NULL,
    DAT_IDENTIFICADOR_RECORRENCIA DATE,
    DHR_EFETIVACAO TIMESTAMPTZ,
    BOL_EXCECAO_RECORRENCIA BOOLEAN NOT NULL DEFAULT FALSE,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK006_TRANSACAO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK006_02_ID_USUARIO_CONTA UNIQUE (ID_REGISTRO, ID_USUARIO, ID_CONTA_FINANCEIRA),
    CONSTRAINT FK006_01_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB001_USUARIO (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT FK006_02_CONTA FOREIGN KEY (ID_CONTA_FINANCEIRA, ID_USUARIO) REFERENCES TB002_CONTA_FINANCEIRA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK006_03_CATEGORIA FOREIGN KEY (ID_CATEGORIA, ID_USUARIO) REFERENCES TB003_CATEGORIA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK006_04_GRUPO FOREIGN KEY (ID_GRUPO_RECORRENCIA, ID_USUARIO) REFERENCES TB004_GRUPO_RECORRENCIA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK006_05_SEGMENTO FOREIGN KEY (ID_SEGMENTO_RECORRENCIA, ID_GRUPO_RECORRENCIA, ID_USUARIO) REFERENCES TB005_SEGMENTO_RECORRENCIA (ID_REGISTRO, ID_GRUPO_RECORRENCIA, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT CK006_01_TIPO CHECK (STR_TIPO IN ('RECEITA', 'DESPESA', 'TRANSFERENCIA')),
    CONSTRAINT CK006_02_STATUS CHECK (STR_STATUS IN ('PLANEJADA', 'EFETIVADA', 'CANCELADA')),
    CONSTRAINT CK006_03_VALOR CHECK (DEC_VALOR > 0),
    CONSTRAINT CK006_04_EFETIVACAO CHECK ((STR_STATUS = 'EFETIVADA') = (DHR_EFETIVACAO IS NOT NULL)),
    CONSTRAINT CK006_05_RECORRENCIA CHECK (
        (ID_SEGMENTO_RECORRENCIA IS NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NULL)
        OR (ID_SEGMENTO_RECORRENCIA IS NOT NULL AND ID_GRUPO_RECORRENCIA IS NOT NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NOT NULL)
    ),
    CONSTRAINT CK006_06_EXCECAO CHECK (
        (BOL_EXCECAO_RECORRENCIA AND ID_GRUPO_RECORRENCIA IS NOT NULL AND ID_SEGMENTO_RECORRENCIA IS NULL)
        OR (NOT BOL_EXCECAO_RECORRENCIA AND (ID_GRUPO_RECORRENCIA IS NULL OR ID_SEGMENTO_RECORRENCIA IS NOT NULL))
    )
);

CREATE TABLE TB007_TRANSFERENCIA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    ID_CONTA_ORIGEM UUID NOT NULL,
    ID_CONTA_DESTINO UUID NOT NULL,
    ID_TRANSACAO_SAIDA UUID NOT NULL,
    ID_TRANSACAO_ENTRADA UUID NOT NULL,
    ID_TRANSFERENCIA_ESTORNADA UUID,
    STR_STATUS VARCHAR(20) NOT NULL,
    STR_DESCRICAO VARCHAR(255) NOT NULL,
    STR_OBSERVACOES VARCHAR(2000),
    DEC_VALOR NUMERIC(19,4) NOT NULL,
    DAT_TRANSFERENCIA DATE NOT NULL,
    DHR_EFETIVACAO TIMESTAMPTZ,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK007_TRANSFERENCIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK007_01_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB001_USUARIO (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT FK007_02_CONTA_ORIGEM FOREIGN KEY (ID_CONTA_ORIGEM, ID_USUARIO) REFERENCES TB002_CONTA_FINANCEIRA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK007_03_CONTA_DESTINO FOREIGN KEY (ID_CONTA_DESTINO, ID_USUARIO) REFERENCES TB002_CONTA_FINANCEIRA (ID_REGISTRO, ID_USUARIO) ON DELETE RESTRICT,
    CONSTRAINT FK007_04_TRANSACAO_SAIDA FOREIGN KEY (ID_TRANSACAO_SAIDA, ID_USUARIO, ID_CONTA_ORIGEM) REFERENCES TB006_TRANSACAO (ID_REGISTRO, ID_USUARIO, ID_CONTA_FINANCEIRA) ON DELETE RESTRICT,
    CONSTRAINT FK007_05_TRANSACAO_ENTRADA FOREIGN KEY (ID_TRANSACAO_ENTRADA, ID_USUARIO, ID_CONTA_DESTINO) REFERENCES TB006_TRANSACAO (ID_REGISTRO, ID_USUARIO, ID_CONTA_FINANCEIRA) ON DELETE RESTRICT,
    CONSTRAINT FK007_06_ESTORNO FOREIGN KEY (ID_TRANSFERENCIA_ESTORNADA) REFERENCES TB007_TRANSFERENCIA (ID_REGISTRO) ON DELETE RESTRICT,
    CONSTRAINT UK007_01_TRANSACAO_SAIDA UNIQUE (ID_TRANSACAO_SAIDA),
    CONSTRAINT UK007_02_TRANSACAO_ENTRADA UNIQUE (ID_TRANSACAO_ENTRADA),
    CONSTRAINT UK007_03_ESTORNO UNIQUE (ID_TRANSFERENCIA_ESTORNADA),
    CONSTRAINT CK007_01_STATUS CHECK (STR_STATUS IN ('PLANEJADA', 'EFETIVADA', 'CANCELADA', 'ESTORNADA')),
    CONSTRAINT CK007_02_CONTAS CHECK (ID_CONTA_ORIGEM <> ID_CONTA_DESTINO),
    CONSTRAINT CK007_03_TRANSACOES CHECK (ID_TRANSACAO_SAIDA <> ID_TRANSACAO_ENTRADA),
    CONSTRAINT CK007_04_VALOR CHECK (DEC_VALOR > 0),
    CONSTRAINT CK007_05_EFETIVACAO CHECK ((STR_STATUS IN ('EFETIVADA', 'ESTORNADA')) = (DHR_EFETIVACAO IS NOT NULL)),
    CONSTRAINT CK007_06_AUTO_ESTORNO CHECK (ID_TRANSFERENCIA_ESTORNADA IS NULL OR ID_TRANSFERENCIA_ESTORNADA <> ID_REGISTRO)
);

CREATE FUNCTION FN007_VALIDAR_TRANSFERENCIA() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    SAIDA TB006_TRANSACAO%ROWTYPE;
    ENTRADA TB006_TRANSACAO%ROWTYPE;
    STATUS_LANCAMENTO VARCHAR(20);
BEGIN
    SELECT * INTO SAIDA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_SAIDA;
    SELECT * INTO ENTRADA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_ENTRADA;
    STATUS_LANCAMENTO := CASE WHEN NEW.STR_STATUS = 'ESTORNADA' THEN 'EFETIVADA' ELSE NEW.STR_STATUS END;

    IF SAIDA.STR_TIPO <> 'TRANSFERENCIA' OR ENTRADA.STR_TIPO <> 'TRANSFERENCIA'
       OR SAIDA.DEC_VALOR <> NEW.DEC_VALOR OR ENTRADA.DEC_VALOR <> NEW.DEC_VALOR
       OR SAIDA.DAT_VENCIMENTO <> NEW.DAT_TRANSFERENCIA OR ENTRADA.DAT_VENCIMENTO <> NEW.DAT_TRANSFERENCIA
       OR SAIDA.STR_STATUS <> STATUS_LANCAMENTO OR ENTRADA.STR_STATUS <> STATUS_LANCAMENTO
       OR SAIDA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO
       OR ENTRADA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO THEN
        RAISE EXCEPTION 'Lancamentos incompatíveis com a transferência %', NEW.ID_REGISTRO;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM TB002_CONTA_FINANCEIRA ORIGEM, TB002_CONTA_FINANCEIRA DESTINO
        WHERE ORIGEM.ID_REGISTRO = NEW.ID_CONTA_ORIGEM
          AND DESTINO.ID_REGISTRO = NEW.ID_CONTA_DESTINO
          AND (ORIGEM.STR_MOEDA <> DESTINO.STR_MOEDA OR NOT ORIGEM.BOL_ATIVO OR NOT DESTINO.BOL_ATIVO)
    ) THEN
        RAISE EXCEPTION 'Contas da transferência devem estar ativas e usar a mesma moeda';
    END IF;
    RETURN NEW;
END;
$FUNCTION$;

CREATE CONSTRAINT TRIGGER TG007_01_VALIDAR_TRANSFERENCIA
AFTER INSERT OR UPDATE ON TB007_TRANSFERENCIA
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION FN007_VALIDAR_TRANSFERENCIA();

CREATE INDEX IX002_01_USUARIO ON TB002_CONTA_FINANCEIRA (ID_USUARIO);
CREATE INDEX IX003_01_USUARIO_CATEGORIA_PAI ON TB003_CATEGORIA (ID_USUARIO, ID_CATEGORIA_PAI);
CREATE INDEX IX004_01_USUARIO_STATUS ON TB004_GRUPO_RECORRENCIA (ID_USUARIO, STR_STATUS);
CREATE INDEX IX005_01_GRUPO_STATUS ON TB005_SEGMENTO_RECORRENCIA (ID_GRUPO_RECORRENCIA, STR_STATUS);
CREATE UNIQUE INDEX UK006_01_OCORRENCIA ON TB006_TRANSACAO (ID_SEGMENTO_RECORRENCIA, DAT_IDENTIFICADOR_RECORRENCIA) WHERE ID_SEGMENTO_RECORRENCIA IS NOT NULL;
CREATE INDEX IX006_01_CONTA_VENCIMENTO ON TB006_TRANSACAO (ID_CONTA_FINANCEIRA, DAT_VENCIMENTO);
CREATE INDEX IX006_02_USUARIO_STATUS_VENCIMENTO ON TB006_TRANSACAO (ID_USUARIO, STR_STATUS, DAT_VENCIMENTO);
CREATE INDEX IX007_01_USUARIO_DATA ON TB007_TRANSFERENCIA (ID_USUARIO, DAT_TRANSFERENCIA);
