ALTER TABLE TB002_CONTA_FINANCEIRA
    ADD COLUMN BOL_DADOS_INICIAIS_BLOQUEADOS BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE TB002_CONTA_FINANCEIRA CONTA
SET BOL_DADOS_INICIAIS_BLOQUEADOS = TRUE
WHERE EXISTS (
    SELECT 1
    FROM TB006_TRANSACAO TRANSACAO
    WHERE TRANSACAO.ID_CONTA_FINANCEIRA = CONTA.ID_REGISTRO
) OR EXISTS (
    SELECT 1
    FROM TB005_SEGMENTO_RECORRENCIA SEGMENTO
    WHERE SEGMENTO.ID_CONTA_FINANCEIRA = CONTA.ID_REGISTRO
);

DO $BLOCK$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM TB006_TRANSACAO TRANSACAO
        JOIN TB002_CONTA_FINANCEIRA CONTA ON CONTA.ID_REGISTRO = TRANSACAO.ID_CONTA_FINANCEIRA
        WHERE TRANSACAO.DAT_VENCIMENTO < CONTA.DAT_SALDO_INICIAL
    ) OR EXISTS (
        SELECT 1
        FROM TB005_SEGMENTO_RECORRENCIA SEGMENTO
        JOIN TB002_CONTA_FINANCEIRA CONTA ON CONTA.ID_REGISTRO = SEGMENTO.ID_CONTA_FINANCEIRA
        WHERE SEGMENTO.DAT_DTSTART < CONTA.DAT_SALDO_INICIAL
    ) THEN
        RAISE EXCEPTION 'Existem operacoes anteriores a data do saldo inicial da conta';
    END IF;
END;
$BLOCK$;

ALTER TABLE TB002_CONTA_FINANCEIRA DROP CONSTRAINT CK002_02_MOEDA;
ALTER TABLE TB002_CONTA_FINANCEIRA
    ADD CONSTRAINT CK002_02_MOEDA CHECK (STR_MOEDA = 'BRL'),
    ADD CONSTRAINT CK002_03_NOME_NORMALIZADO CHECK (STR_NOME !~ '^[[:space:]]|[[:space:]]$');

CREATE UNIQUE INDEX IX002_02_NOME_USUARIO
    ON TB002_CONTA_FINANCEIRA (ID_USUARIO, LOWER(STR_NOME));

CREATE FUNCTION FN002_PROTEGER_DADOS_INICIAIS() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    IF OLD.BOL_DADOS_INICIAIS_BLOQUEADOS AND NOT NEW.BOL_DADOS_INICIAIS_BLOQUEADOS THEN
        RAISE EXCEPTION 'O bloqueio dos dados iniciais da conta e irreversivel';
    END IF;

    IF OLD.BOL_DADOS_INICIAIS_BLOQUEADOS AND (
        NEW.STR_MOEDA IS DISTINCT FROM OLD.STR_MOEDA
        OR NEW.DEC_SALDO_INICIAL IS DISTINCT FROM OLD.DEC_SALDO_INICIAL
        OR NEW.DAT_SALDO_INICIAL IS DISTINCT FROM OLD.DAT_SALDO_INICIAL
    ) THEN
        RAISE EXCEPTION 'Os dados iniciais da conta estao bloqueados';
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE TRIGGER TG002_01_PROTEGER_DADOS_INICIAIS
BEFORE UPDATE ON TB002_CONTA_FINANCEIRA
FOR EACH ROW EXECUTE FUNCTION FN002_PROTEGER_DADOS_INICIAIS();

CREATE FUNCTION FN006_VALIDAR_CONTA_TRANSACAO() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    CONTA TB002_CONTA_FINANCEIRA%ROWTYPE;
BEGIN
    SELECT * INTO CONTA
    FROM TB002_CONTA_FINANCEIRA
    WHERE ID_REGISTRO = NEW.ID_CONTA_FINANCEIRA
    FOR UPDATE;

    IF FOUND THEN
        IF TG_OP = 'INSERT' AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Novas transacoes exigem conta ativa';
        ELSIF TG_OP = 'UPDATE'
              AND NEW.ID_CONTA_FINANCEIRA IS DISTINCT FROM OLD.ID_CONTA_FINANCEIRA
              AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Uma nova associacao exige conta ativa';
        END IF;

        IF NEW.DAT_VENCIMENTO < CONTA.DAT_SALDO_INICIAL THEN
            RAISE EXCEPTION 'A data financeira e anterior a data do saldo inicial da conta';
        END IF;
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE TRIGGER TG006_01_VALIDAR_CONTA
BEFORE INSERT OR UPDATE OF ID_CONTA_FINANCEIRA, DAT_VENCIMENTO ON TB006_TRANSACAO
FOR EACH ROW EXECUTE FUNCTION FN006_VALIDAR_CONTA_TRANSACAO();

CREATE FUNCTION FN005_VALIDAR_CONTA_SEGMENTO() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    CONTA TB002_CONTA_FINANCEIRA%ROWTYPE;
BEGIN
    SELECT * INTO CONTA
    FROM TB002_CONTA_FINANCEIRA
    WHERE ID_REGISTRO = NEW.ID_CONTA_FINANCEIRA
    FOR UPDATE;

    IF FOUND THEN
        IF TG_OP = 'INSERT' AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Novos segmentos exigem conta ativa';
        ELSIF TG_OP = 'UPDATE'
              AND NEW.ID_CONTA_FINANCEIRA IS DISTINCT FROM OLD.ID_CONTA_FINANCEIRA
              AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Uma nova associacao exige conta ativa';
        END IF;

        IF NEW.DAT_DTSTART < CONTA.DAT_SALDO_INICIAL THEN
            RAISE EXCEPTION 'O inicio do segmento e anterior a data do saldo inicial da conta';
        END IF;
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE TRIGGER TG005_01_VALIDAR_CONTA
BEFORE INSERT OR UPDATE OF ID_CONTA_FINANCEIRA, DAT_DTSTART ON TB005_SEGMENTO_RECORRENCIA
FOR EACH ROW EXECUTE FUNCTION FN005_VALIDAR_CONTA_SEGMENTO();

CREATE FUNCTION FN002_BLOQUEAR_DADOS_INICIAIS() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
    UPDATE TB002_CONTA_FINANCEIRA
    SET BOL_DADOS_INICIAIS_BLOQUEADOS = TRUE
    WHERE ID_REGISTRO = NEW.ID_CONTA_FINANCEIRA
      AND NOT BOL_DADOS_INICIAIS_BLOQUEADOS;
    RETURN NEW;
END;
$FUNCTION$;

CREATE TRIGGER TG006_02_BLOQUEAR_DADOS_INICIAIS
AFTER INSERT OR UPDATE OF ID_CONTA_FINANCEIRA ON TB006_TRANSACAO
FOR EACH ROW EXECUTE FUNCTION FN002_BLOQUEAR_DADOS_INICIAIS();

CREATE TRIGGER TG005_02_BLOQUEAR_DADOS_INICIAIS
AFTER INSERT OR UPDATE OF ID_CONTA_FINANCEIRA ON TB005_SEGMENTO_RECORRENCIA
FOR EACH ROW EXECUTE FUNCTION FN002_BLOQUEAR_DADOS_INICIAIS();

CREATE OR REPLACE FUNCTION FN007_VALIDAR_TRANSFERENCIA() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    SAIDA TB006_TRANSACAO%ROWTYPE;
    ENTRADA TB006_TRANSACAO%ROWTYPE;
    ORIGEM TB002_CONTA_FINANCEIRA%ROWTYPE;
    DESTINO TB002_CONTA_FINANCEIRA%ROWTYPE;
    STATUS_LANCAMENTO VARCHAR(20);
BEGIN
    SELECT * INTO SAIDA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_SAIDA;
    SELECT * INTO ENTRADA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_ENTRADA;
    STATUS_LANCAMENTO := CASE WHEN NEW.STR_STATUS = 'ESTORNADA' THEN 'EFETIVADA' ELSE NEW.STR_STATUS END;

    IF SAIDA.STR_TIPO <> 'TRANSFERENCIA' OR ENTRADA.STR_TIPO <> 'TRANSFERENCIA'
       OR SAIDA.DEC_VALOR <> NEW.DEC_VALOR OR ENTRADA.DEC_VALOR <> NEW.DEC_VALOR
       OR SAIDA.DAT_VENCIMENTO <> NEW.DAT_TRANSFERENCIA OR ENTRADA.DAT_VENCIMENTO <> NEW.DAT_TRANSFERENCIA
       OR SAIDA.STR_STATUS <> STATUS_LANCAMENTO OR ENTRADA.STR_STATUS <> STATUS_LANCAMENTO
       OR SAIDA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO
       OR ENTRADA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO THEN
        RAISE EXCEPTION 'Transacoes incompativeis com a transferencia %', NEW.ID_REGISTRO;
    END IF;

    SELECT * INTO ORIGEM FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_ORIGEM;
    SELECT * INTO DESTINO FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_DESTINO;

    IF ORIGEM.STR_MOEDA <> DESTINO.STR_MOEDA THEN
        RAISE EXCEPTION 'Contas da transferencia devem usar a mesma moeda';
    END IF;

    IF TG_OP = 'INSERT' AND (NOT ORIGEM.BOL_ATIVO OR NOT DESTINO.BOL_ATIVO) THEN
        RAISE EXCEPTION 'Novas transferencias exigem contas ativas';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_ORIGEM IS DISTINCT FROM OLD.ID_CONTA_ORIGEM
       AND NOT ORIGEM.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de origem deve estar ativa';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_DESTINO IS DISTINCT FROM OLD.ID_CONTA_DESTINO
       AND NOT DESTINO.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de destino deve estar ativa';
    END IF;

    RETURN NEW;
END;
$FUNCTION$;
