DELETE FROM TB007_TRANSFERENCIA
WHERE STR_STATUS = 'CANCELADA';

DELETE FROM TB006_TRANSACAO
WHERE STR_STATUS = 'CANCELADA';

ALTER TABLE TB006_TRANSACAO
    RENAME COLUMN STR_STATUS TO STR_SITUACAO;

ALTER TABLE TB006_TRANSACAO
    RENAME COLUMN DAT_VENCIMENTO TO DAT_FINANCEIRA;

ALTER TABLE TB006_TRANSACAO
    DROP CONSTRAINT CK006_02_STATUS;

ALTER TABLE TB006_TRANSACAO
    ADD CONSTRAINT CK006_02_SITUACAO CHECK (STR_SITUACAO IN ('PLANEJADA', 'EFETIVADA'));

ALTER INDEX IX006_01_CONTA_VENCIMENTO RENAME TO IX006_01_CONTA_DATA_FINANCEIRA;
ALTER INDEX IX006_02_USUARIO_STATUS_VENCIMENTO RENAME TO IX006_02_USUARIO_SITUACAO_DATA_FINANCEIRA;

CREATE OR REPLACE FUNCTION FN006_VALIDAR_CONTA_TRANSACAO() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    CONTA TB002_CONTA_FINANCEIRA%ROWTYPE;
BEGIN
    SELECT * INTO CONTA
    FROM TB002_CONTA_FINANCEIRA
    WHERE ID_REGISTRO = NEW.ID_CONTA_FINANCEIRA
    FOR UPDATE;

    IF FOUND THEN
        IF TG_OP = 'INSERT' AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Novas transacoes exigem conta ativa';
        ELSIF TG_OP = 'UPDATE'
              AND NEW.ID_CONTA_FINANCEIRA IS DISTINCT FROM OLD.ID_CONTA_FINANCEIRA
              AND NOT CONTA.BOL_ATIVO THEN
            RAISE EXCEPTION 'Uma nova associacao exige conta ativa';
        END IF;

        IF NEW.DAT_FINANCEIRA < CONTA.DAT_SALDO_INICIAL THEN
            RAISE EXCEPTION 'A data financeira e anterior a data do saldo inicial da conta';
        END IF;
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE OR REPLACE FUNCTION FN007_VALIDAR_TRANSFERENCIA() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    SAIDA TB006_TRANSACAO%ROWTYPE;
    ENTRADA TB006_TRANSACAO%ROWTYPE;
    ORIGEM TB002_CONTA_FINANCEIRA%ROWTYPE;
    DESTINO TB002_CONTA_FINANCEIRA%ROWTYPE;
    STATUS_LANCAMENTO VARCHAR(20);
BEGIN
    SELECT * INTO SAIDA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_SAIDA;
    SELECT * INTO ENTRADA FROM TB006_TRANSACAO WHERE ID_REGISTRO = NEW.ID_TRANSACAO_ENTRADA;
    STATUS_LANCAMENTO := CASE WHEN NEW.STR_STATUS = 'ESTORNADA' THEN 'EFETIVADA' ELSE NEW.STR_STATUS END;

    IF SAIDA.STR_TIPO <> 'TRANSFERENCIA' OR ENTRADA.STR_TIPO <> 'TRANSFERENCIA'
       OR SAIDA.DEC_VALOR <> NEW.DEC_VALOR OR ENTRADA.DEC_VALOR <> NEW.DEC_VALOR
       OR SAIDA.DAT_FINANCEIRA <> NEW.DAT_TRANSFERENCIA OR ENTRADA.DAT_FINANCEIRA <> NEW.DAT_TRANSFERENCIA
       OR SAIDA.STR_SITUACAO <> STATUS_LANCAMENTO OR ENTRADA.STR_SITUACAO <> STATUS_LANCAMENTO
       OR SAIDA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO
       OR ENTRADA.DHR_EFETIVACAO IS DISTINCT FROM NEW.DHR_EFETIVACAO THEN
        RAISE EXCEPTION 'Transacoes incompativeis com a transferencia %', NEW.ID_REGISTRO;
    END IF;

    SELECT * INTO ORIGEM FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_ORIGEM;
    SELECT * INTO DESTINO FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_DESTINO;

    IF ORIGEM.STR_MOEDA <> DESTINO.STR_MOEDA THEN
        RAISE EXCEPTION 'Contas da transferencia devem usar a mesma moeda';
    END IF;

    IF TG_OP = 'INSERT' AND (NOT ORIGEM.BOL_ATIVO OR NOT DESTINO.BOL_ATIVO) THEN
        RAISE EXCEPTION 'Novas transferencias exigem contas ativas';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_ORIGEM IS DISTINCT FROM OLD.ID_CONTA_ORIGEM
       AND NOT ORIGEM.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de origem deve estar ativa';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_DESTINO IS DISTINCT FROM OLD.ID_CONTA_DESTINO
       AND NOT DESTINO.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de destino deve estar ativa';
    END IF;

    RETURN NEW;
END;
$FUNCTION$;
