DROP TRIGGER TG007_01_VALIDAR_TRANSFERENCIA ON TB007_TRANSFERENCIA;
DROP FUNCTION FN007_VALIDAR_TRANSFERENCIA();

DO $BLOCK$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM TB006_TRANSACAO TRANSACAO
        WHERE TRANSACAO.STR_TIPO = 'TRANSFERENCIA'
          AND NOT EXISTS (
              SELECT 1
              FROM TB007_TRANSFERENCIA TRANSFERENCIA
              WHERE TRANSFERENCIA.ID_TRANSACAO_SAIDA = TRANSACAO.ID_REGISTRO
                 OR TRANSFERENCIA.ID_TRANSACAO_ENTRADA = TRANSACAO.ID_REGISTRO
          )
    ) THEN
        RAISE EXCEPTION 'Existem Transacoes de Transferencia sem vinculo com uma Transferencia';
    END IF;
END;
$BLOCK$;

UPDATE TB007_TRANSFERENCIA
SET STR_STATUS = 'EFETIVADA',
    ID_TRANSFERENCIA_ESTORNADA = NULL
WHERE STR_STATUS = 'ESTORNADA';

UPDATE TB006_TRANSACAO TRANSACAO
SET ID_USUARIO = TRANSFERENCIA.ID_USUARIO,
    ID_CONTA_FINANCEIRA = TRANSFERENCIA.ID_CONTA_ORIGEM,
    ID_CATEGORIA = NULL,
    ID_GRUPO_RECORRENCIA = NULL,
    ID_SEGMENTO_RECORRENCIA = NULL,
    STR_TIPO = 'DESPESA',
    STR_SITUACAO = TRANSFERENCIA.STR_STATUS,
    STR_DESCRICAO = TRANSFERENCIA.STR_DESCRICAO,
    STR_OBSERVACOES = TRANSFERENCIA.STR_OBSERVACOES,
    DEC_VALOR = TRANSFERENCIA.DEC_VALOR,
    DAT_FINANCEIRA = TRANSFERENCIA.DAT_TRANSFERENCIA,
    DAT_IDENTIFICADOR_RECORRENCIA = NULL,
    DHR_EFETIVACAO = TRANSFERENCIA.DHR_EFETIVACAO,
    BOL_EXCECAO_RECORRENCIA = FALSE
FROM TB007_TRANSFERENCIA TRANSFERENCIA
WHERE TRANSACAO.ID_REGISTRO = TRANSFERENCIA.ID_TRANSACAO_SAIDA;

UPDATE TB006_TRANSACAO TRANSACAO
SET ID_USUARIO = TRANSFERENCIA.ID_USUARIO,
    ID_CONTA_FINANCEIRA = TRANSFERENCIA.ID_CONTA_DESTINO,
    ID_CATEGORIA = NULL,
    ID_GRUPO_RECORRENCIA = NULL,
    ID_SEGMENTO_RECORRENCIA = NULL,
    STR_TIPO = 'RECEITA',
    STR_SITUACAO = TRANSFERENCIA.STR_STATUS,
    STR_DESCRICAO = TRANSFERENCIA.STR_DESCRICAO,
    STR_OBSERVACOES = TRANSFERENCIA.STR_OBSERVACOES,
    DEC_VALOR = TRANSFERENCIA.DEC_VALOR,
    DAT_FINANCEIRA = TRANSFERENCIA.DAT_TRANSFERENCIA,
    DAT_IDENTIFICADOR_RECORRENCIA = NULL,
    DHR_EFETIVACAO = TRANSFERENCIA.DHR_EFETIVACAO,
    BOL_EXCECAO_RECORRENCIA = FALSE
FROM TB007_TRANSFERENCIA TRANSFERENCIA
WHERE TRANSACAO.ID_REGISTRO = TRANSFERENCIA.ID_TRANSACAO_ENTRADA;

ALTER TABLE TB006_TRANSACAO DROP CONSTRAINT CK006_01_TIPO;
ALTER TABLE TB006_TRANSACAO
    ADD CONSTRAINT CK006_01_TIPO CHECK (STR_TIPO IN ('RECEITA', 'DESPESA'));

ALTER TABLE TB007_TRANSFERENCIA DROP CONSTRAINT FK007_06_ESTORNO;
ALTER TABLE TB007_TRANSFERENCIA DROP CONSTRAINT UK007_03_ESTORNO;
ALTER TABLE TB007_TRANSFERENCIA DROP CONSTRAINT CK007_01_STATUS;
ALTER TABLE TB007_TRANSFERENCIA DROP CONSTRAINT CK007_05_EFETIVACAO;
ALTER TABLE TB007_TRANSFERENCIA DROP CONSTRAINT CK007_06_AUTO_ESTORNO;
ALTER TABLE TB007_TRANSFERENCIA DROP COLUMN ID_TRANSFERENCIA_ESTORNADA;

ALTER TABLE TB007_TRANSFERENCIA RENAME COLUMN STR_STATUS TO STR_SITUACAO;
ALTER TABLE TB007_TRANSFERENCIA RENAME COLUMN DAT_TRANSFERENCIA TO DAT_FINANCEIRA;
ALTER INDEX IX007_01_USUARIO_DATA RENAME TO IX007_01_USUARIO_DATA_FINANCEIRA;

ALTER TABLE TB007_TRANSFERENCIA
    ADD CONSTRAINT CK007_01_SITUACAO CHECK (STR_SITUACAO IN ('PLANEJADA', 'EFETIVADA')),
    ADD CONSTRAINT CK007_05_EFETIVACAO CHECK (
        (STR_SITUACAO = 'EFETIVADA') = (DHR_EFETIVACAO IS NOT NULL)
    );

CREATE FUNCTION FN007_VERIFICAR_TRANSFERENCIA(P_TRANSFERENCIA_ID UUID) RETURNS VOID
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    TRANSFERENCIA TB007_TRANSFERENCIA%ROWTYPE;
    SAIDA TB006_TRANSACAO%ROWTYPE;
    ENTRADA TB006_TRANSACAO%ROWTYPE;
BEGIN
    SELECT * INTO TRANSFERENCIA
    FROM TB007_TRANSFERENCIA
    WHERE ID_REGISTRO = P_TRANSFERENCIA_ID;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    SELECT * INTO SAIDA FROM TB006_TRANSACAO WHERE ID_REGISTRO = TRANSFERENCIA.ID_TRANSACAO_SAIDA;
    SELECT * INTO ENTRADA FROM TB006_TRANSACAO WHERE ID_REGISTRO = TRANSFERENCIA.ID_TRANSACAO_ENTRADA;

    IF SAIDA.ID_REGISTRO IS NULL OR ENTRADA.ID_REGISTRO IS NULL
       OR SAIDA.STR_TIPO <> 'DESPESA'
       OR ENTRADA.STR_TIPO <> 'RECEITA'
       OR SAIDA.ID_CATEGORIA IS NOT NULL
       OR ENTRADA.ID_CATEGORIA IS NOT NULL
       OR SAIDA.ID_GRUPO_RECORRENCIA IS NOT NULL
       OR ENTRADA.ID_GRUPO_RECORRENCIA IS NOT NULL
       OR SAIDA.ID_SEGMENTO_RECORRENCIA IS NOT NULL
       OR ENTRADA.ID_SEGMENTO_RECORRENCIA IS NOT NULL
       OR SAIDA.DAT_IDENTIFICADOR_RECORRENCIA IS NOT NULL
       OR ENTRADA.DAT_IDENTIFICADOR_RECORRENCIA IS NOT NULL
       OR SAIDA.BOL_EXCECAO_RECORRENCIA
       OR ENTRADA.BOL_EXCECAO_RECORRENCIA
       OR SAIDA.STR_SITUACAO <> TRANSFERENCIA.STR_SITUACAO
       OR ENTRADA.STR_SITUACAO <> TRANSFERENCIA.STR_SITUACAO
       OR SAIDA.STR_DESCRICAO <> TRANSFERENCIA.STR_DESCRICAO
       OR ENTRADA.STR_DESCRICAO <> TRANSFERENCIA.STR_DESCRICAO
       OR SAIDA.STR_OBSERVACOES IS DISTINCT FROM TRANSFERENCIA.STR_OBSERVACOES
       OR ENTRADA.STR_OBSERVACOES IS DISTINCT FROM TRANSFERENCIA.STR_OBSERVACOES
       OR SAIDA.DEC_VALOR <> TRANSFERENCIA.DEC_VALOR
       OR ENTRADA.DEC_VALOR <> TRANSFERENCIA.DEC_VALOR
       OR SAIDA.DAT_FINANCEIRA <> TRANSFERENCIA.DAT_FINANCEIRA
       OR ENTRADA.DAT_FINANCEIRA <> TRANSFERENCIA.DAT_FINANCEIRA
       OR SAIDA.DHR_EFETIVACAO IS DISTINCT FROM TRANSFERENCIA.DHR_EFETIVACAO
       OR ENTRADA.DHR_EFETIVACAO IS DISTINCT FROM TRANSFERENCIA.DHR_EFETIVACAO THEN
        RAISE EXCEPTION 'Transacoes incompativeis com a Transferencia %', P_TRANSFERENCIA_ID;
    END IF;
END;
$FUNCTION$;

CREATE FUNCTION FN007_VALIDAR_TRANSFERENCIA() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    ORIGEM TB002_CONTA_FINANCEIRA%ROWTYPE;
    DESTINO TB002_CONTA_FINANCEIRA%ROWTYPE;
BEGIN
    PERFORM FN007_VERIFICAR_TRANSFERENCIA(NEW.ID_REGISTRO);

    SELECT * INTO ORIGEM FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_ORIGEM;
    SELECT * INTO DESTINO FROM TB002_CONTA_FINANCEIRA WHERE ID_REGISTRO = NEW.ID_CONTA_DESTINO;

    IF ORIGEM.STR_MOEDA <> DESTINO.STR_MOEDA THEN
        RAISE EXCEPTION 'Contas da Transferencia devem usar a mesma moeda';
    END IF;
    IF TG_OP = 'INSERT' AND (NOT ORIGEM.BOL_ATIVO OR NOT DESTINO.BOL_ATIVO) THEN
        RAISE EXCEPTION 'Novas Transferencias exigem contas ativas';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_ORIGEM IS DISTINCT FROM OLD.ID_CONTA_ORIGEM
       AND NOT ORIGEM.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de origem deve estar ativa';
    END IF;
    IF TG_OP = 'UPDATE'
       AND NEW.ID_CONTA_DESTINO IS DISTINCT FROM OLD.ID_CONTA_DESTINO
       AND NOT DESTINO.BOL_ATIVO THEN
        RAISE EXCEPTION 'Uma nova conta de destino deve estar ativa';
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE CONSTRAINT TRIGGER TG007_01_VALIDAR_TRANSFERENCIA
AFTER INSERT OR UPDATE ON TB007_TRANSFERENCIA
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION FN007_VALIDAR_TRANSFERENCIA();

CREATE FUNCTION FN006_VALIDAR_LADO_TRANSFERENCIA() RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    TRANSFERENCIA_ID UUID;
BEGIN
    SELECT ID_REGISTRO INTO TRANSFERENCIA_ID
    FROM TB007_TRANSFERENCIA
    WHERE ID_TRANSACAO_SAIDA = NEW.ID_REGISTRO
       OR ID_TRANSACAO_ENTRADA = NEW.ID_REGISTRO;

    IF TRANSFERENCIA_ID IS NOT NULL THEN
        PERFORM FN007_VERIFICAR_TRANSFERENCIA(TRANSFERENCIA_ID);
    END IF;

    RETURN NEW;
END;
$FUNCTION$;

CREATE CONSTRAINT TRIGGER TG006_03_VALIDAR_LADO_TRANSFERENCIA
AFTER INSERT OR UPDATE ON TB006_TRANSACAO
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION FN006_VALIDAR_LADO_TRANSFERENCIA();
