ALTER TABLE TB004_GRUPO_RECORRENCIA
    ADD COLUMN STR_TIPO VARCHAR(20) NOT NULL DEFAULT 'RECORRENCIA',
    ADD CONSTRAINT CK004_03_TIPO CHECK (STR_TIPO IN ('RECORRENCIA', 'PARCELAMENTO'));

ALTER TABLE TB005_SEGMENTO_RECORRENCIA
    ADD COLUMN DAT_FIM DATE,
    ADD COLUMN INT_NUMERO_PRIMEIRA_PARCELA INTEGER,
    ADD COLUMN INT_QUANTIDADE_TOTAL_ORIGINAL INTEGER,
    ADD CONSTRAINT CK005_05_FIM CHECK (DAT_FIM IS NULL OR DAT_FIM >= DAT_DTSTART),
    ADD CONSTRAINT CK005_06_NUMERO_PARCELA CHECK (
        INT_NUMERO_PRIMEIRA_PARCELA IS NULL OR INT_NUMERO_PRIMEIRA_PARCELA > 0
    ),
    ADD CONSTRAINT CK005_07_QUANTIDADE_PARCELA CHECK (
        INT_QUANTIDADE_TOTAL_ORIGINAL IS NULL OR INT_QUANTIDADE_TOTAL_ORIGINAL > 0
    ),
    ADD CONSTRAINT CK005_08_PARCELA_COMPLETA CHECK (
        (
            INT_NUMERO_PRIMEIRA_PARCELA IS NULL
            AND INT_QUANTIDADE_TOTAL_ORIGINAL IS NULL
        )
        OR (
            INT_NUMERO_PRIMEIRA_PARCELA IS NOT NULL
            AND INT_QUANTIDADE_TOTAL_ORIGINAL IS NOT NULL
            AND INT_NUMERO_PRIMEIRA_PARCELA <= INT_QUANTIDADE_TOTAL_ORIGINAL
        )
    );

ALTER TABLE TB006_TRANSACAO DROP CONSTRAINT CK006_06_EXCECAO;

ALTER TABLE TB006_TRANSACAO
    ADD CONSTRAINT CK006_06_EXCECAO CHECK (
        (
            BOL_EXCECAO_RECORRENCIA
            AND ID_GRUPO_RECORRENCIA IS NOT NULL
            AND (
                (ID_SEGMENTO_RECORRENCIA IS NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NULL)
                OR (ID_SEGMENTO_RECORRENCIA IS NOT NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NOT NULL)
            )
        )
        OR (
            NOT BOL_EXCECAO_RECORRENCIA
            AND (
                (ID_GRUPO_RECORRENCIA IS NULL AND ID_SEGMENTO_RECORRENCIA IS NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NULL)
                OR (ID_GRUPO_RECORRENCIA IS NOT NULL AND ID_SEGMENTO_RECORRENCIA IS NOT NULL AND DAT_IDENTIFICADOR_RECORRENCIA IS NOT NULL)
            )
        )
    );

CREATE TABLE TB008_SUPRESSAO_RECORRENCIA (
    ID_REGISTRO UUID NOT NULL,
    ID_USUARIO UUID NOT NULL,
    ID_GRUPO_RECORRENCIA UUID NOT NULL,
    ID_SEGMENTO_RECORRENCIA UUID NOT NULL,
    DAT_IDENTIFICADOR_RECORRENCIA DATE NOT NULL,
    DHR_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DHR_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REGISTRO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK008_SUPRESSAO_RECORRENCIA PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT UK008_01_ID_USUARIO_SEGMENTO_DATA UNIQUE (
        ID_SEGMENTO_RECORRENCIA,
        DAT_IDENTIFICADOR_RECORRENCIA
    ),
    CONSTRAINT FK008_01_SEGMENTO FOREIGN KEY (
        ID_SEGMENTO_RECORRENCIA,
        ID_GRUPO_RECORRENCIA,
        ID_USUARIO
    ) REFERENCES TB005_SEGMENTO_RECORRENCIA (
        ID_REGISTRO,
        ID_GRUPO_RECORRENCIA,
        ID_USUARIO
    ) ON DELETE RESTRICT
);

CREATE INDEX IX008_01_USUARIO_SEGMENTO
    ON TB008_SUPRESSAO_RECORRENCIA (ID_USUARIO, ID_SEGMENTO_RECORRENCIA);
